// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Forçar o uso do engine "binary" em vez do engine "client",
  // que exige um adapter ou accelerateUrl. Isso gera o Prisma Client
  // com o engine binário tradicional.
  datasource: {
    url: process.env.DATABASE_URL,
  },
};
